# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # bcrypt from FOSUser
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
    # Role for administration
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER


    # On utilise FOSUser comme fournisseur de sécurité
    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                 provider: fos_userbundle
                 csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/article/, role: ROLE_USER }
            - { path: ^/admin/section/, role: ROLE_ADMIN }
